[package]
name = "rsml"
version = "0.1.0"
authors = ["suchin"]

[dependencies]
ndarray = "*"
ndarray-rand = "*"

typenum = "1.2.*"
rand="*"
rayon="*"

rust-tfidf = "*"

[lib]
name="rsml"
path="src/lib.rs"

[[bin]]
name="rsml"
path="src/main.rs"

[profile.release]
debug=true
